name: Tag on version change

on:
  push:
    branches:
      - main

jobs:
  tag-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.6
        with:
          fetch-depth: 2  # Traz pelo menos 2 commits para que HEAD^ esteja disponível
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '16'

      - name: Check if package.json changed
        id: package-json-changed
        run: |
          #git fetch origin main
          if git diff --name-only HEAD^ HEAD | grep -q 'package.json'; then
            echo "package.json changed"
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "package.json did not change"
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Get current package version
        if: steps.package-json-changed.outputs.changed == 'true'
        id: pkg
        run: echo "version=$(jq -r .version < package.json)" >> $GITHUB_ENV

      - name: Get previous version
        if: steps.package-json-changed.outputs.changed == 'true'
        id: prev_ver
        run: |
          git fetch --tags
          PREV_TAG=$(git tag --list --sort=-v:refname | head -n 1)
          if [ -z "$PREV_TAG" ]; then
            echo "prev_version=0.0.0" >> $GITHUB_ENV
          else
            echo "prev_version=${PREV_TAG#v}" >> $GITHUB_ENV
          fi

      - name: Compare versions and create tag
        if: steps.package-json-changed.outputs.changed == 'true'
        run: |
          new_version=$(jq -r .version < package.json)
          if [ "$new_version" != "$prev_version" ]; then
            git config --global user.name 'Heliomar P. Marques'
            git config --global user.email 'heliomarpm@gmail.com'
            git tag "v$new_version"
            git push origin "v$new_version"
          fi
        env:
          version: ${{ env.version }}
          prev_version: ${{ env.prev_version }}
